@BASE_URL = http://127.0.0.1:8000/api
@token = Bearer 2|SSPX3ztk3miJBxud4gPzfnNYXh21WM1l0252SBhSeb96d038

###

# Change Password
PATCH {{BASE_URL}}/auth/change-password
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "current_password": "admin123",
  "new_password": "admin1234",
  "new_password_confirmation": "admin1234"
}

###

# GET
GET {{BASE_URL}}/users
Content-Type: application/json

### 

# GET
GET {{BASE_URL}}/users/01960be3-384d-70d6-8b3c-c2b648297496
Content-Type: application/json

###

# POST
POST {{BASE_URL}}/users
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "Admin2",
  "email": "admin3@gmail.com",
  "password": "admin123"
}

###

# PUT without image
PUT {{BASE_URL}}/users/01960be3-384d-70d6-8b3c-c2b648297496
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "kamu333",
  "email": "admin@gmail.com",
  "password": "admin123"
}

###

# DELETE
DELETE {{BASE_URL}}/users/2
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

# ==============================
# AUTH
### Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Admin",
  "email": "admin@gmail.com",
  "password": "admin123",
  "password_confirmation": "admin123"
}

### Login
POST {{BASE_URL}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@gmail.com",
  "password": "admin123"
}

### Chekk Auth
GET {{BASE_URL}}/auth/me
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

### Logout
POST {{BASE_URL}}/auth/logout
Content-Type: application/json
Accept: application/json
Authorization: {{token}}


# ======================================================================================
# name and email only
curl -X POST "http://127.0.0.1:8000/api/users/01960bd8-e7c2-70c7-af09-fe3e24f074e8" `
--header "Authorization: Bearer 2|SSPX3ztk3miJBxud4gPzfnNYXh21WM1l0252SBhSeb96d038" `
--header "Accept: application/json" `
--form "_method=PUT" `
--form "name=name" `
--form "email=email@sajaaaa.com"

# picture only
curl -X POST "http://127.0.0.1:8000/api/users/01960bd8-e7c2-70c7-af09-fe3e24f074e8" `
--header "Authorization: Bearer 2|SSPX3ztk3miJBxud4gPzfnNYXh21WM1l0252SBhSeb96d038" `
--header "Accept: application/json" `
--form "_method=PUT" `
--form "picture=@D:\Salman\say.jpeg"

# name, email, and picture
curl -X POST "http://127.0.0.1:8000/api/users/01960bd8-e7c2-70c7-af09-fe3e24f074e8" `
--header "Authorization: Bearer 2|SSPX3ztk3miJBxud4gPzfnNYXh21WM1l0252SBhSeb96d038" `
--header "Accept: application/json" `
--form "_method=PUT" `
--form "name=John Doe" `
--form "email=johndoe@example.com" `
--form "picture=@D:\Salman\ggp.png"